name: 'transcript_analysis'
version: '1.0.0'
config-version: 2

profile: 'transcript_analysis'

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  transcript_analysis:
    staging:
      +materialized: view
    marts:
      +materialized: table
    insights:
      +materialized: table
